CREATE TABLE USERINFO 
(	
	USER_ID VARCHAR2(255 BYTE) NOT NULL, 
	PASSWORD VARCHAR2(255 BYTE) NOT NULL, 
	CONSTRAINT USERINFO_PK PRIMARY KEY (USER_ID)
)

CREATE TABLE BILL(
	BILL_ID INTEGER NOT NULL,
	CREATE_DATE DATE NOT NULL,
	USER_ID VARCHAR2(255),
	CONSTRAINT FK_BILL_USERINFO FOREIGN KEY (USER_ID) REFERENCES USERINFO(USER_ID),
	CONSTRAINT PK_BILL PRIMARY KEY (BILL_ID)
);

CREATE TABLE BILL_LINE_ITEM(
	ITEM_ID INTEGER NOT NULL,
	ITEM_NAME VARCHAR2(255) NOT NULL,
	ITEM_COST NUMBER(*,2) NOT NULL,
	BILL_ID INTEGER NOT NULL,
	CONSTRAINT PK_LINE_ITEM PRIMARY KEY (ITEM_ID),
	CONSTRAINT FK_LINE_ITEM_BILL FOREIGN KEY (BILL_ID) REFERENCES BILL(BILL_ID)
);

--CREATE SEQUENCE BILL_SEQUENCE INCREMENT BY 1 START WITH 1 CACHE 20;
--CREATE SEQUENCE BILL_LINE_ITEM_SEQUENCE INCREMENT BY 1 START WITH 1 CACHE 20;

create or replace procedure addTestDataProc
as
  i number;
begin
  dbms_output.put_line('Start insert data...');
  delete from bill where bill_id='1';
  delete from userinfo where user_id='test';
  insert into userinfo values ('test', '123456');
  insert into bill values (1, SYSDATE(), 'test');
  for i in 1..1000000 
  loop
    insert into bill_line_item values(i, 'itemName'||i, i, 1);
  end loop;
end;
/

